/**
 * Generates `src/data/vendorMarks.ts` — the vendor logo paths — from the
 * `simple-icons` package.
 *
 *     pnpm marks:publish
 *
 * ## Why a generated module and not SVG files in public/
 *
 * The obvious version writes `public/brand/vendors/google.svg` and points an
 * `<img>` at it. That ships a logo nobody can see: an SVG loaded through `<img>`
 * is an isolated document, page CSS does not reach inside it, and
 * `fill="currentColor"` resolves against the file's own default — black, on a
 * near-black canvas. Half of these brands are `#000000`.
 *
 * Inlining the path solves it at the root: the mark is part of the page, takes
 * `currentColor` like any other glyph, and costs no request at all — which
 * matters more here than usual, since the model wall draws nineteen of them.
 *
 * ## The mapping is explicit on purpose
 *
 * Fuzzy-matching a vendor name against 3,453 icon titles is how you ship the
 * wrong logo. Doing exactly that during this work produced `xAI → X` (Twitter),
 * `Tongyi → TON` (a blockchain), `Recraft → R` (the R language) and
 * `Black Forest Labs → Black`. Each would have rendered as a confident, wrong
 * brand mark. Every entry below is a slug somebody checked.
 *
 * ## Vendors deliberately absent
 *
 * simple-icons has no icon for OpenAI, Black Forest Labs, Ideogram, xAI, Tongyi,
 * Topaz Labs or Recraft — its "OpenAI Gym" entry is a different product and is
 * not a substitute. Those families keep the monogram, which is a working state:
 * `VendorMark` is the floor under all of this.
 *
 * These are other companies' trademarks. Shipping them asserts they may be used
 * to indicate compatibility — a per-brand judgement, made once, recorded here.
 */
import { writeFileSync } from "node:fs";
import * as simpleIcons from "simple-icons";

/** Vendor string in `src/data/models.ts` → simple-icons slug. Checked by hand. */
const VENDOR_SLUGS: Record<string, string> = {
  Google: "google",
  ByteDance: "bytedance",
  Alibaba: "alibabacloud",
  Kuaishou: "kuaishou",
  MiniMax: "minimax",
  ElevenLabs: "elevenlabs",
};

interface SimpleIcon {
  title: string;
  slug: string;
  path: string;
}

const icons = Object.values(simpleIcons as Record<string, unknown>).filter(
  (icon): icon is SimpleIcon => typeof icon === "object" && icon !== null && "slug" in icon && "path" in icon && "title" in icon,
);
const bySlug = new Map(icons.map((icon) => [icon.slug, icon]));

const rows: string[] = [];
const missing: string[] = [];

for (const [vendor, slug] of Object.entries(VENDOR_SLUGS)) {
  const icon = bySlug.get(slug);
  if (!icon) {
    missing.push(`${vendor} → ${slug}`);
    continue;
  }
  rows.push(`  /** ${icon.title} — simple-icons \`${slug}\` */\n  ${JSON.stringify(vendor)}: ${JSON.stringify(icon.path)},`);
  console.log(`  ${vendor.padEnd(14)} → ${icon.title}  (${icon.path.length} chars)`);
}

if (missing.length) {
  console.error(`\nUNRESOLVED SLUGS — fix the mapping:\n  ${missing.join("\n  ")}`);
  process.exit(1);
}

const file = `// GENERATED by scripts/publish-vendor-marks.ts — do not edit by hand.
// Run \`pnpm marks:publish\` to regenerate. The vendor→slug mapping, and the
// reasoning for which vendors are here at all, live in that script.
//
// Single-path SVG outlines on a 24×24 viewBox, drawn with \`currentColor\` so a
// row of them reads as one system rather than as a sticker sheet — and so the
// brands whose colour is #000000 are visible on a near-black canvas.

export const VENDOR_MARK_PATHS: Record<string, string> = {
${rows.join("\n")}
};

/** simple-icons draws everything on this box. */
export const VENDOR_MARK_VIEWBOX = "0 0 24 24";
`;

writeFileSync("src/data/vendorMarks.ts", file);
console.log(`\n${rows.length} vendor marks written to src/data/vendorMarks.ts`);
