// What a generation costs, for the screens that have to show a number before
// the user commits to it.
//
// This used to be 44 rate functions plus a live overlay fetched from KIE. Both
// are gone. Prices are rows now — `model_prices` in Postgres, seeded from
// `pricing.rows.json`, which is the same list this file reads. The server
// prices from the table and the browser prices from the list the table was
// built from, through the one algorithm in @vgen/core, so the number under the
// Create button and the number the ledger charges cannot disagree.
//
// The browser reading a committed copy is deliberate and temporary. A price
// shown before submitting has to render without a round trip, and
// `POST /generation/quotes` does not exist yet. When it does, these screens ask
// the server and this file goes; until then the copy is generated, never
// hand-edited, and a CI check pins it to the database.
//
// Economics (locked):
//   1 coin = $0.05 to the user · margin 2x · KIE credit = $0.005
//
// The pivot is USD, not provider credits, so adding a second provider does not
// touch the coin economy.

import { isRefusal, resolvePrice, type PriceRefusal, type PriceRowLike } from "@vgen/core";
import priceList from "./pricing.rows.json";
import { defaultInput, variantControls, type Family, type Variant } from "./models";
import type { InputMap } from "../components/controls";

// KIE_CREDIT_USD and coinsForKieCredits are deliberately not re-exported: the
// names alone say who we buy from, and nothing in the browser prices in a
// supplier's unit. They remain available to server code from @vgen/core.
export { COIN_USD, MARGIN, MICRO_CREDITS_PER_COIN, coinsFor } from "@vgen/core";

/**
 * What the caller knows that the settings do not say.
 *
 * `chars` is the prompt length, for the speech models billed by it. Kept as a
 * separate argument rather than folded into the settings because it is not a
 * control the user sets — it is a consequence of what they typed.
 */
export interface PriceCtx {
  chars: number;
  clipSeconds: number;
}

export const NO_CTX: PriceCtx = { chars: 0, clipSeconds: 0 };

/**
 * A row as the browser gets it.
 *
 * Generated by `scripts/build-price-list.ts` from `upstream.pricing.json`, which
 * additionally carries the supplier's path and what a generation costs us. Both
 * are stripped on purpose: sitting beside `microCredits` they are our margin,
 * and a JSON import is inlined into the bundle whether or not any code reads it.
 *
 * `resolvePrice` still computes a `providerUnits` from the zeroes below and
 * `coinsForVariantId` still throws it away, exactly as before. No displayed
 * number moves.
 */
interface StoredRow {
  variantId: string;
  selector: Record<string, string>;
  pricingMode: "fixed" | "derived";
  quantity: "none" | "seconds" | "characters";
  microCredits: number;
  maxBillableUnits: number | null;
  isOffered: boolean;
}

/** Grouped once at module load; the list is static and every screen reads it. */
const ROWS_BY_VARIANT = new Map<string, PriceRowLike[]>();
for (const row of (priceList as { rows: StoredRow[] }).rows) {
  const shaped: PriceRowLike = {
    selector: row.selector,
    pricingMode: row.pricingMode,
    isOffered: row.isOffered,
    // Zero, not a cost. The browser prices in coins; what a generation costs us
    // is the server's business and stays on the server.
    providerUnitsBase: 0,
    providerUnitsPerSecond: 0,
    providerUnitsPer1kInput: 0,
    microCreditsBase: row.quantity === "none" ? row.microCredits : 0,
    microCreditsPerSecond: row.quantity === "seconds" ? row.microCredits : 0,
    microCreditsPer1kInput: row.quantity === "characters" ? row.microCredits : 0,
    maxBillableUnits: row.maxBillableUnits,
  };
  ROWS_BY_VARIANT.set(row.variantId, [...(ROWS_BY_VARIANT.get(row.variantId) ?? []), shaped]);
}

/**
 * Billable seconds for a variant, which is not always the duration control.
 *
 * A duration of zero means "keep the whole source clip" on the video editors, so
 * the length then comes from the file the user attached and is not known until
 * it lands. The upscalers and Motion Control have no duration control at all.
 */
function billableSeconds(input: InputMap, ctx: PriceCtx): number {
  const duration = Number(input.duration);
  return Number.isFinite(duration) && duration > 0 ? duration : ctx.clipSeconds;
}

/** Coins for a generation, or null when the combination cannot be priced or sold. */
export function priceCoins(variant: Variant, input: InputMap, ctx: PriceCtx = NO_CTX): number | null {
  return coinsForVariantId(variant.id, input, ctx);
}

/**
 * The same, for a caller holding an id rather than the variant.
 *
 * `plans.ts` prices its estimate anchors this way: it names two models by id to
 * work out what a plan's coins buy, and importing the whole catalogue to look
 * up an object it already knows the id of would be a cycle.
 */
export function coinsForVariantId(variantId: string, input: InputMap, ctx: PriceCtx = NO_CTX): number | null {
  const rows = ROWS_BY_VARIANT.get(variantId);
  if (!rows) return null;
  const outcome = resolvePrice(rows, { params: input, seconds: billableSeconds(input, ctx), characters: ctx.chars });
  return isRefusal(outcome) ? null : outcome.coins;
}

/**
 * *Why* a combination has no price, for the one screen that has to say so.
 *
 * `priceCoins` answers `null` to three different questions, and the API is
 * explicit that two of them are not the same thing: `not_offered` is a product
 * decision — Hailuo 2.3 genuinely has no 1080P at ten seconds — and the button
 * should simply say so. `no_matching_row` and `missing_quantity` mean our own
 * price list failed to cover a combination the catalogue still offers, which is
 * a bug on our side, and telling somebody "this isn't supported" hides it behind
 * a sentence that sounds deliberate.
 *
 * Returns null when the combination *is* priced, so a caller reads it as "no
 * refusal" rather than having to compare against a success value it does not
 * need.
 */
export function priceRefusal(variant: Variant, input: InputMap, ctx: PriceCtx = NO_CTX): PriceRefusal | null {
  const rows = ROWS_BY_VARIANT.get(variant.id);
  if (!rows) return "no_matching_row";
  const outcome = resolvePrice(rows, { params: input, seconds: billableSeconds(input, ctx), characters: ctx.chars });
  return isRefusal(outcome) ? outcome : null;
}

/** The cheapest a family can be run for, for the "from N coins" line on Landing. */
export function minCoinsForFamily(family: Family): number | null {
  const prices = family.variants
    .map((variant) => priceCoins(variant, defaultInput(variantControls(family, variant)), NO_CTX))
    .filter((coins): coins is number => coins !== null);
  return prices.length ? Math.min(...prices) : null;
}
